package com.miniscreen.takeover;

import android.app.*;
import android.app.job.*;
import android.content.*;
import android.content.pm.*;
import android.net.Uri;
import android.os.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;

/** Public GitHub releases; no GitHub credentials, no background installation. */
final class AppUpdates {
 static final String REPOSITORY="wer-wie-was/MiniScreen-Takeover",CHANNEL="app-updates";
 static final int JOB=50500,NOTICE=50501;static final long DAY=86400000L,MAX_APK=256L*1024*1024;
 static final ExecutorService worker=Executors.newSingleThreadExecutor();static final AtomicBoolean busy=new AtomicBoolean();
 static SharedPreferences prefs(Context c){return TakeoverControl.prefs(c);}
 static File apk(Context c){return new File(c.getCacheDir(),"takeover-update.apk");}
 static void state(Context c,String state){prefs(c).edit().putString("update_state",state).apply();}
 static void schedule(Context c){try{JobScheduler jobs=(JobScheduler)c.getSystemService(Context.JOB_SCHEDULER_SERVICE);if(!prefs(c).getBoolean("update_auto",true)){jobs.cancel(JOB);return;}if(jobs.getPendingJob(JOB)==null)jobs.schedule(new JobInfo.Builder(JOB,new ComponentName(c,UpdateJob.class)).setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY).setPeriodic(DAY).setPersisted(true).build());}catch(RuntimeException e){android.util.Log.w("AppUpdates","Unable to schedule update check",e);state(c,"failed");}}
 static void check(Context context,boolean force,Runnable done){Context c=context.getApplicationContext();if(!busy.compareAndSet(false,true)){if(done!=null)done.run();return;}worker.execute(()->{try{
  long last=prefs(c).getLong("update_checked",0);if(!force&&System.currentTimeMillis()-last<DAY)return;state(c,"checking");
  HttpURLConnection conn=open("https://api.github.com/repos/"+REPOSITORY+"/releases/latest");conn.setRequestProperty("Accept","application/vnd.github+json");conn.setRequestProperty("X-GitHub-Api-Version","2022-11-28");JSONObject release;
  try{int code=conn.getResponseCode();if(code==404){prefs(c).edit().putLong("update_checked",System.currentTimeMillis()).putString("update_release","").apply();state(c,"current");return;}if(code!=200)throw new IOException("Release HTTP "+code);try(InputStream in=conn.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){PebbleFiles.copy(in,out,2*1024*1024);release=new JSONObject(out.toString("UTF-8"));}}finally{conn.disconnect();}
  if(release.optBoolean("draft")||release.optBoolean("prerelease"))throw new IOException("Not a stable release");String tag=release.getString("tag_name");boolean newer=compare(tag,AppVersion.name(c))>0;JSONObject asset=selectAsset(release.getJSONArray("assets"),tag);if(newer&&asset==null)throw new IOException("No unique APK asset");
  String previous=prefs(c).getString("update_release","");SharedPreferences.Editor edit=prefs(c).edit().putLong("update_checked",System.currentTimeMillis()).putString("update_release",newer?tag:"").putString("update_notes",release.optString("body","").substring(0,Math.min(16000,release.optString("body","").length())));
  if(newer)edit.putString("update_url",asset.getString("browser_download_url")).putString("update_digest",asset.optString("digest","")).putLong("update_size",asset.getLong("size"));if(!tag.equals(previous))edit.remove("update_ready");edit.apply();state(c,newer?"available":"current");
  if(newer&&!tag.equals(prefs(c).getString("update_skip",""))&&!tag.equals(prefs(c).getString("update_notified",""))){if(notifyUpdate(c)){prefs(c).edit().putString("update_notified",tag).apply();}}
 }catch(Exception e){state(c,"failed");}finally{busy.set(false);new Handler(Looper.getMainLooper()).post(UpdateActivity::refreshForeground);if(done!=null)done.run();}});}
 static int compare(String a,String b)throws IOException{int[] x=version(a),y=version(b);for(int i=0;i<3;i++)if(x[i]!=y[i])return Integer.compare(x[i],y[i]);return 0;}
 static int[] version(String tag)throws IOException{String v=tag.startsWith("v")?tag.substring(1):tag;if(!v.matches("[0-9]+\\.[0-9]+\\.[0-9]+"))throw new IOException("Invalid version tag");String[] parts=v.split("\\.");try{return new int[]{Integer.parseInt(parts[0]),Integer.parseInt(parts[1]),Integer.parseInt(parts[2])};}catch(NumberFormatException e){throw new IOException(e);}}
 static JSONObject selectAsset(JSONArray all,String tag){JSONObject candidate=null;int count=0;for(int i=0;i<all.length();i++){JSONObject a=all.optJSONObject(i);if(a==null||!a.optString("name").toLowerCase(Locale.ROOT).endsWith(".apk")||!"uploaded".equals(a.optString("state")))continue;String n=a.optString("name");if(n.equalsIgnoreCase("MiniScreenTakeover-"+(tag.startsWith("v")?tag.substring(1):tag)+".apk"))return a;count++;candidate=a;}return count==1?candidate:null;}
 static HttpURLConnection open(String url)throws IOException{URL u=new URL(url);String host=u.getHost().toLowerCase(Locale.ROOT);if(!"https".equals(u.getProtocol())||u.getUserInfo()!=null||!(host.equals("api.github.com")||host.equals("github.com")||host.endsWith(".githubusercontent.com")))throw new IOException("Untrusted download host");HttpURLConnection conn=(HttpURLConnection)u.openConnection();conn.setInstanceFollowRedirects(false);conn.setConnectTimeout(15000);conn.setReadTimeout(20000);conn.setRequestProperty("User-Agent","MiniScreenTakeover");return conn;}
 static HttpURLConnection downloadConnection(String url)throws IOException{for(int i=0;i<6;i++){HttpURLConnection c=open(url);int status=c.getResponseCode();if(status==200)return c;if(status==301||status==302||status==303||status==307||status==308){String location=c.getHeaderField("Location");c.disconnect();if(location==null)throw new IOException("Missing redirect");url=new URL(new URL(url),location).toString();continue;}c.disconnect();throw new IOException("APK HTTP "+status);}throw new IOException("Redirect limit");}
 static void download(Context context){Context c=context.getApplicationContext();if(!busy.compareAndSet(false,true))return;worker.execute(()->{File tmp=new File(apk(c).getPath()+".part");boolean ready=false;try{String tag=prefs(c).getString("update_release","");if(tag.isEmpty()||compare(tag,AppVersion.name(c))<=0)throw new IOException("No update");state(c,"downloading");prefs(c).edit().putInt("update_progress",0).apply();long expected=prefs(c).getLong("update_size",0);if(expected<1||expected>MAX_APK)throw new IOException("APK size");MessageDigest hash=MessageDigest.getInstance("SHA-256");HttpURLConnection conn=downloadConnection(prefs(c).getString("update_url",""));long total=0,lastProgress=0;
  try(InputStream in=conn.getInputStream();OutputStream out=new FileOutputStream(tmp)){byte[] buffer=new byte[32768];int count;while((count=in.read(buffer))!=-1){total+=count;if(total>expected||total>MAX_APK)throw new IOException("APK exceeds size");hash.update(buffer,0,count);out.write(buffer,0,count);if(SystemClock.elapsedRealtime()-lastProgress>500){lastProgress=SystemClock.elapsedRealtime();prefs(c).edit().putInt("update_progress",(int)(total*100/expected)).apply();}}}finally{conn.disconnect();}if(total!=expected)throw new IOException("Incomplete APK");String digest=prefs(c).getString("update_digest","");if(!digest.isEmpty()&&!digest.equalsIgnoreCase("sha256:"+hex(hash.digest())))throw new IOException("Digest mismatch");validate(c,tmp);java.nio.file.Files.move(tmp.toPath(),apk(c).toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);prefs(c).edit().putString("update_ready",tag).putInt("update_progress",100).apply();state(c,"ready");ready=true;
 }catch(Exception e){tmp.delete();state(c,"failed");}finally{busy.set(false);new Handler(Looper.getMainLooper()).post(UpdateActivity::refreshForeground);if(ready)new Handler(Looper.getMainLooper()).post(()->UpdateActivity.installIfForeground(c));}});}
 static String hex(byte[] bytes){StringBuilder b=new StringBuilder();for(byte n:bytes)b.append(String.format(Locale.ROOT,"%02x",n&255));return b.toString();}
 static long code(PackageInfo p){return Build.VERSION.SDK_INT>=28?p.getLongVersionCode():p.versionCode;}
 static Set<String> certificates(PackageInfo p)throws Exception{android.content.pm.Signature[] certs=Build.VERSION.SDK_INT>=28?(p.signingInfo==null?null:p.signingInfo.getApkContentsSigners()):p.signatures;if(certs==null||certs.length==0)throw new IOException("Missing signatures");Set<String> result=new HashSet<>();for(android.content.pm.Signature s:certs)result.add(hex(MessageDigest.getInstance("SHA-256").digest(s.toByteArray())));return result;}
 static void validate(Context c,File file)throws Exception{PackageManager pm=c.getPackageManager();int flags=Build.VERSION.SDK_INT>=28?PackageManager.GET_SIGNING_CERTIFICATES:PackageManager.GET_SIGNATURES;PackageInfo next=pm.getPackageArchiveInfo(file.getPath(),flags),current=pm.getPackageInfo(c.getPackageName(),flags);if(next==null||!c.getPackageName().equals(next.packageName)||code(next)<=code(current)||!certificates(next).equals(certificates(current)))throw new IOException("Package, version or signature mismatch");}
 static void install(Activity activity){Context c=activity.getApplicationContext();if(!c.getPackageManager().canRequestPackageInstalls()){activity.startActivity(new Intent(android.provider.Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+c.getPackageName())));return;}if(!busy.compareAndSet(false,true))return;state(c,"installing");worker.execute(()->{PackageInstaller.Session session=null;int id=-1;try{validate(c,apk(c));PackageInstaller installer=c.getPackageManager().getPackageInstaller();PackageInstaller.SessionParams params=new PackageInstaller.SessionParams(PackageInstaller.SessionParams.MODE_FULL_INSTALL);params.setAppPackageName(c.getPackageName());params.setSize(apk(c).length());if(Build.VERSION.SDK_INT>=31)params.setRequireUserAction(PackageInstaller.SessionParams.USER_ACTION_REQUIRED);id=installer.createSession(params);session=installer.openSession(id);try(InputStream in=new FileInputStream(apk(c));OutputStream out=session.openWrite("base.apk",0,apk(c).length())){PebbleFiles.copy(in,out,MAX_APK);session.fsync(out);}Intent result=new Intent(c,UpdateInstallReceiver.class).setAction(c.getPackageName()+".UPDATE_RESULT");PendingIntent callback=PendingIntent.getBroadcast(c,id,result,PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=31?PendingIntent.FLAG_MUTABLE:0));session.commit(callback.getIntentSender());}catch(Exception e){if(id>=0)try{c.getPackageManager().getPackageInstaller().abandonSession(id);}catch(RuntimeException ignored){}state(c,"failed");}finally{if(session!=null)session.close();busy.set(false);new Handler(Looper.getMainLooper()).post(UpdateActivity::refreshForeground);}});}
 static NotificationManager notifications(Context c){NotificationManager n=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);n.createNotificationChannel(new NotificationChannel(CHANNEL,I18n.get(R.string.update_title),NotificationManager.IMPORTANCE_DEFAULT));return n;}
 static boolean notifyUpdate(Context c){try{NotificationManager n=notifications(c);if(!n.areNotificationsEnabled())return false;PendingIntent open=PendingIntent.getActivity(c,NOTICE,new Intent(c,UpdateActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);n.notify(NOTICE,new Notification.Builder(c,CHANNEL).setSmallIcon(android.R.drawable.stat_sys_download_done).setContentTitle(I18n.get(R.string.update_available)+" "+prefs(c).getString("update_release","")).setContentText(I18n.get(R.string.update_download)).setContentIntent(open).setAutoCancel(true).build());return true;}catch(SecurityException e){return false;}}
}
