package com.miniscreen.takeover;
import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.widget.*;
import java.util.*;
import java.text.Normalizer;
import java.util.regex.Pattern;
import org.json.*;

/** Device-only rules. Raw notification text is checked before privacy redaction, never saved. */
final class TickerWordFilter {
 static String normalized(String text){return Normalizer.normalize(text,Normalizer.Form.NFKC).toLowerCase(Locale.ROOT);}
 static List<String> words(SharedPreferences p){List<String> result=new ArrayList<>();try{JSONArray a=new JSONArray(p.getString("ticker_filter_words","[]"));for(int i=0;i<Math.min(100,a.length());i++){String word=a.optString(i).trim();if(!word.isEmpty()&&word.length()<=128)result.add(word);}}catch(JSONException ignored){}return result;}
 static boolean blocked(Context c,String... text){SharedPreferences p=TakeoverControl.prefs(c);if(!p.getBoolean("ticker_filter_enabled",false))return false;List<String> words=words(p);boolean whole=p.getBoolean("ticker_filter_whole",false);for(String value:text){if(value==null)continue;String input=normalized(value);for(String word:words){String match=normalized(word);if(whole?Pattern.compile("(?<![\\p{L}\\p{N}_])"+Pattern.quote(match)+"(?![\\p{L}\\p{N}_])").matcher(input).find():input.contains(match))return true;}}return false;}
 static boolean blockedNotification(Context c,Notification n){if(!TakeoverControl.prefs(c).getBoolean("ticker_filter_enabled",false)||n.extras==null)return false;Bundle extras=n.extras;for(String key:new String[]{Notification.EXTRA_TITLE,Notification.EXTRA_TITLE_BIG,Notification.EXTRA_TEXT,Notification.EXTRA_BIG_TEXT,Notification.EXTRA_SUB_TEXT}){CharSequence value=extras.getCharSequence(key);if(value!=null&&blocked(c,value.toString()))return true;}CharSequence[] lines=extras.getCharSequenceArray(Notification.EXTRA_TEXT_LINES);if(lines!=null)for(CharSequence value:lines)if(value!=null&&blocked(c,value.toString()))return true;android.os.Parcelable[] messages=extras.getParcelableArray(Notification.EXTRA_MESSAGES);if(messages!=null)for(android.os.Parcelable item:messages)if(item instanceof Bundle){CharSequence value=((Bundle)item).getCharSequence("text");if(value!=null&&blocked(c,value.toString()))return true;}return false;}
 static void show(Context c,Runnable changed){SharedPreferences p=TakeoverControl.prefs(c);List<String> draft=new ArrayList<>(words(p));LinearLayout box=new LinearLayout(c);box.setOrientation(1);int pad=Math.round(16*c.getResources().getDisplayMetrics().density);box.setPadding(pad,pad,pad,pad);
  Switch enabled=new Switch(c);enabled.setText(I18n.get(R.string.ticker_filter_enable));enabled.setChecked(p.getBoolean("ticker_filter_enabled",false));box.addView(enabled);Spinner mode=new Spinner(c);mode.setAdapter(new ArrayAdapter<String>(c,android.R.layout.simple_spinner_dropdown_item,new String[]{I18n.get(R.string.ticker_filter_contains),I18n.get(R.string.ticker_filter_whole)}));mode.setSelection(p.getBoolean("ticker_filter_whole",false)?1:0);box.addView(mode);TextView help=new TextView(c);help.setText(I18n.get(R.string.ticker_filter_help));box.addView(help);
  EditText input=new EditText(c);input.setSingleLine(true);input.setHint(I18n.get(R.string.ticker_filter_keyword));input.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(128)});box.addView(input);Button add=new Button(c);add.setText(I18n.get(R.string.ticker_filter_add));box.addView(add);ScrollView scroll=new ScrollView(c);LinearLayout list=new LinearLayout(c);list.setOrientation(1);scroll.addView(list);box.addView(scroll,new LinearLayout.LayoutParams(-1,pad*12));
  Runnable[] render=new Runnable[1];render[0]=()->{list.removeAllViews();for(String word:new ArrayList<>(draft)){LinearLayout row=new LinearLayout(c);TextView label=new TextView(c);label.setText(word);row.addView(label,new LinearLayout.LayoutParams(0,-2,1));Button remove=new Button(c);remove.setText("−");remove.setContentDescription(I18n.get(R.string.ticker_filter_remove)+": "+word);remove.setOnClickListener(v->{draft.remove(word);render[0].run();});row.addView(remove);list.addView(row);}};render[0].run();add.setOnClickListener(v->{String word=input.getText().toString().trim();if(word.isEmpty())return;if(draft.size()>=100){input.setError(I18n.get(R.string.ticker_filter_limit));return;}for(String old:draft)if(normalized(old).equals(normalized(word))){input.setText("");return;}draft.add(word);input.setText("");render[0].run();});
  new AlertDialog.Builder(c).setTitle(I18n.get(R.string.ticker_word_filter)).setView(box).setNegativeButton(android.R.string.cancel,null).setPositiveButton(android.R.string.ok,(d,w)->{JSONArray a=new JSONArray();for(String word:draft)a.put(word);p.edit().putBoolean("ticker_filter_enabled",enabled.isChecked()).putBoolean("ticker_filter_whole",mode.getSelectedItemPosition()==1).putString("ticker_filter_words",a.toString()).apply();NotificationTicker.settingsChanged(c);TickerListener.refreshNow();changed.run();}).show();
 }
}
