package com.miniscreen.takeover;
import android.app.*;
import android.content.*;
import android.os.*;
import android.widget.*;
import java.lang.ref.WeakReference;

public final class UpdateActivity extends Activity implements SharedPreferences.OnSharedPreferenceChangeListener {
 private static WeakReference<UpdateActivity> foreground=new WeakReference<>(null);private boolean requestedInstall,waitingPermission;private TextView status;private Button install;private ProgressBar progress;
 @Override protected void attachBaseContext(Context c){super.attachBaseContext(I18n.wrap(c));}
 @Override public void onCreate(Bundle saved){super.onCreate(saved);if(saved!=null){requestedInstall=saved.getBoolean("requested");waitingPermission=saved.getBoolean("permission");}LinearLayout box=new LinearLayout(this);box.setOrientation(1);int pad=Math.round(18*getResources().getDisplayMetrics().density);box.setPadding(pad,pad,pad,pad);ScrollView scroll=new ScrollView(this);scroll.addView(box);setContentView(scroll);TextView title=new TextView(this);title.setText(I18n.get(R.string.update_title)+" · "+AppVersion.name(this));title.setTextSize(22);box.addView(title);TextView repo=new TextView(this);repo.setText("github.com/"+AppUpdates.REPOSITORY);box.addView(repo);
  Switch automatic=new Switch(this);automatic.setText(I18n.get(R.string.update_auto));automatic.setChecked(AppUpdates.prefs(this).getBoolean("update_auto",true));box.addView(automatic);automatic.setOnCheckedChangeListener((v,value)->{AppUpdates.prefs(this).edit().putBoolean("update_auto",value).apply();AppUpdates.schedule(this);});TextView explanation=new TextView(this);explanation.setText(I18n.get(R.string.update_help));box.addView(explanation);status=new TextView(this);box.addView(status);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);box.addView(progress);
  add(box,I18n.get(R.string.update_check),()->AppUpdates.check(this,true,null));install=add(box,I18n.get(R.string.update_download),()->{requestedInstall=true;startFlow();});add(box,I18n.get(R.string.update_notes),()->new AlertDialog.Builder(this).setTitle(I18n.get(R.string.update_notes)).setMessage(AppUpdates.prefs(this).getString("update_notes","")).setPositiveButton(android.R.string.ok,null).show());add(box,I18n.get(R.string.update_skip),()->{AppUpdates.prefs(this).edit().putString("update_skip",AppUpdates.prefs(this).getString("update_release","")).apply();AppUpdates.notifications(this).cancel(AppUpdates.NOTICE);requestedInstall=false;refresh();});refresh();}
 private Button add(LinearLayout box,String text,Runnable action){Button b=new Button(this);b.setText(text);b.setAllCaps(false);box.addView(b);b.setOnClickListener(v->action.run());return b;}
 private void startFlow(){String tag=AppUpdates.prefs(this).getString("update_release","");if(tag.isEmpty())return;if(!getPackageManager().canRequestPackageInstalls()){waitingPermission=true;startActivity(new Intent(android.provider.Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,android.net.Uri.parse("package:"+getPackageName())));return;}waitingPermission=false;if(tag.equals(AppUpdates.prefs(this).getString("update_ready",""))&&AppUpdates.apk(this).isFile())AppUpdates.install(this);else AppUpdates.download(this);}
 static void refreshForeground(){UpdateActivity a=foreground.get();if(a!=null&&!a.isFinishing())a.refresh();}
 static void installIfForeground(Context c){UpdateActivity a=foreground.get();if(a!=null&&!a.isFinishing()&&a.requestedInstall)a.startFlow();else AppUpdates.notifyUpdate(c);}
 static boolean confirmIfForeground(Intent intent){UpdateActivity a=foreground.get();if(a==null||a.isFinishing())return false;try{a.requestedInstall=false;a.startActivity(intent);return true;}catch(RuntimeException e){return false;}}
 static String statusText(Context c){String state=AppUpdates.prefs(c).getString("update_state","");int id=state.equals("checking")?R.string.update_checking:state.equals("downloading")?R.string.update_downloading:state.equals("ready")?R.string.update_ready:state.equals("installing")?R.string.update_confirm:state.equals("failed")?R.string.update_failed:state.equals("current")?R.string.update_current:state.equals("available")?R.string.update_available:R.string.update_check;return I18n.get(id);}
 private void refresh(){status.setText(statusText(this)+" "+AppUpdates.prefs(this).getString("update_release",""));progress.setProgress(AppUpdates.prefs(this).getInt("update_progress",0));progress.setVisibility("downloading".equals(AppUpdates.prefs(this).getString("update_state",""))?android.view.View.VISIBLE:android.view.View.GONE);install.setEnabled(!AppUpdates.busy.get()&&!AppUpdates.prefs(this).getString("update_release","").isEmpty());}
 @Override protected void onResume(){super.onResume();foreground=new WeakReference<>(this);AppUpdates.prefs(this).registerOnSharedPreferenceChangeListener(this);refresh();if(waitingPermission){waitingPermission=false;if(getPackageManager().canRequestPackageInstalls())startFlow();else requestedInstall=false;}}
 @Override protected void onPause(){if(foreground.get()==this)foreground.clear();AppUpdates.prefs(this).unregisterOnSharedPreferenceChangeListener(this);super.onPause();}
 @Override protected void onSaveInstanceState(Bundle b){b.putBoolean("requested",requestedInstall);b.putBoolean("permission",waitingPermission);super.onSaveInstanceState(b);}
 @Override public void onSharedPreferenceChanged(SharedPreferences p,String key){if(key.startsWith("update_"))refresh();}
}
